module.exports.authService = require('./auth.service');
// module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.homePageService = require('./homepage.service');
module.exports.destinationService = require('./destination.service');
module.exports.holidayService = require('./holiday.service');
module.exports.pageMetaService = require('./pagemeta.service');
module.exports.menuService= require('./menu.service')
